INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status) VALUES ('华为', '华为技术有限公司', 100, '万物互联', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ('小米', '小米科技有限公司', 50, 'are you ok', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ('格力', '格力电器股份有限公司', 30, '让世界爱上中国造', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ('阿里巴巴', '阿里巴巴集团控股有限公司', 10, '买买买', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ('腾讯', '腾讯计算机系统有限公司', 50, '玩玩玩', 0);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ('百度', '百度在线网络技术公司', 5, '搜搜搜', 0);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ('京东', '北京京东世纪贸易有限公司', 40, '就是快', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ('小米', '小米科技有限公司', 50, 'are you ok', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ('三只松鼠', '三只松鼠股份有限公司', 5, '好吃不上火', 0);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '华为', '华为技术有限公司', 100, '万物互联', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '小米', '小米科技有限公司', 50, 'are you ok', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '格力', '格力电器股份有限公司', 30, '让世界爱上中国造', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '阿里巴巴', '阿里巴巴集团控股有限公司', 10, '买买买', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '腾讯', '腾讯计算机系统有限公司', 50, '玩玩玩', 0);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '百度', '百度在线网络技术公司', 5, '搜搜搜', 0);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '京东', '北京京东世纪贸易有限公司', 40, '就是快', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '华为', '华为技术有限公司', 100, '万物互联', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '小米', '小米科技有限公司', 50, 'are you ok', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '格力', '格力电器股份有限公司', 30, '让世界爱上中国造', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '阿里巴巴', '阿里巴巴集团控股有限公司', 10, '买买买', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '腾讯', '腾讯计算机系统有限公司', 50, '玩玩玩', 0);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '百度', '百度在线网络技术公司', 5, '搜搜搜', 0);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '京东', '北京京东世纪贸易有限公司', 40, '就是快', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '小米', '小米科技有限公司', 50, 'are you ok', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '三只松鼠', '三只松鼠股份有限公司', 5, '好吃不上火', 0);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '华为', '华为技术有限公司', 100, '万物互联', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '小米', '小米科技有限公司', 50, 'are you ok', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '格力', '格力电器股份有限公司', 30, '让世界爱上中国造', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '阿里巴巴', '阿里巴巴集团控股有限公司', 10, '买买买', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '腾讯', '腾讯计算机系统有限公司', 50, '玩玩玩', 0);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '百度', '百度在线网络技术公司', 5, '搜搜搜', 0);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '京东', '北京京东世纪贸易有限公司', 40, '就是快', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '华为', '华为技术有限公司', 100, '万物互联', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '小米', '小米科技有限公司', 50, 'are you ok', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '格力', '格力电器股份有限公司', 30, '让世界爱上中国造', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '阿里巴巴', '阿里巴巴集团控股有限公司', 10, '买买买', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '腾讯', '腾讯计算机系统有限公司', 50, '玩玩玩', 0);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '百度', '百度在线网络技术公司', 5, '搜搜搜', 0);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '京东', '北京京东世纪贸易有限公司', 40, '就是快', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '小米', '小米科技有限公司', 50, 'are you ok', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '三只松鼠', '三只松鼠股份有限公司', 5, '好吃不上火', 0);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '华为', '华为技术有限公司', 100, '万物互联', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '小米', '小米科技有限公司', 50, 'are you ok', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '格力', '格力电器股份有限公司', 30, '让世界爱上中国造', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '阿里巴巴', '阿里巴巴集团控股有限公司', 10, '买买买', 1);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '腾讯', '腾讯计算机系统有限公司', 50, '玩玩玩', 0);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '百度', '百度在线网络技术公司', 5, '搜搜搜', 0);
INSERT INTO `tb_brand`(brand_name,company_name,ordered,description,status)  VALUES ( '京东', '北京京东世纪贸易有限公司', 40, '就是快', 1);